project_name: devk
release:
  github:
    owner: izzatzr
    name: devk
builds:
  - id: devk
    goos:
    - linux
    - windows
    - darwin
    goarch:
    - amd64
    - "386"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: cmd/plugin/main.go
    ldflags: -s -w
      -X github.com/izzatzr/devk/pkg/version.version=
archives:
  - id: devk
    builds:
    - devk
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
    - goos: windows
      format: zip
