apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: devk
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/izzatzr/devk/releases/download/v0.1.0/devk_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./devk"
      to: "."
    - from: LICENSE
      to: "."
    bin: "devk"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/izzatzr/devk/releases/download/v0.1.0/devk_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./devk"
      to: "."
    - from: LICENSE
      to: "."
    bin: "devk"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/izzatzr/devk/releases/download/v0.1.0/devk_windows_amd64.zip
    sha256: ""
    files:
    - from: "/devk.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "devk.exe"
  shortDescription: A new plugin
  homepage: https://github.com/izzatzr/devk
  caveats: |
    Usage:
      $ kubectl devk

    For additional options:
      $ kubectl devk --help
      or https://github.com/izzatzr/devk/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a new plugin
